name: GameTimeKit CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Swift version
        run: swift --version
      - name: Test package
        run: swift test
